Repository BlackToppStudios/Jagati, pull requests merged in 2019-01, with the labels that each got.

#78 Added Mezzy package and touched up readme.
  Jagati.cmake
  JagatiIndex.cmake
  README.md
  SHA512SUM.txt
Labels: enhancement, perfective

#79 Feature-c++17
  .travis.yml
  Jagati.cmake
  SHA512SUM.txt
Labels: enhancement

#80 Bug-SHAFix
  .travis.yml
  Jagati.cmake
  Jenkinsfile
  SHA512SUM.txt
Labels: bug, enhancement

#81 Added linker flag for coverage to clang on mac os x
  Jagati.cmake
  SHA512SUM.txt
Labels: bug
